services:
  - type: web
    name: budgetory-backend
    runtime: docker
    dockerfilePath: ./backend/docker/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/healthcheck
    plan: free
    envVars:
      - key: ENV_FOR_DYNACONF
        value: production
      - key: DYNACONF_ENVIRONMENT__SECRET_KEY
        generateValue: true
      - key: DYNACONF_ENVIRONMENT__SUPERUSER_API_KEY
        generateValue: true
      - key: DATABASE
        value: postgres
      - key: SQL_HOST
        fromDatabase:
          name: budgetory-db
          property: host
      - key: SQL_PORT
        fromDatabase:
          name: budgetory-db
          property: port
      - key: DYNACONF_DATABASE__USER
        fromDatabase:
          name: budgetory-db
          property: user
      - key: DYNACONF_DATABASE__PASSWORD
        fromDatabase:
          name: budgetory-db
          property: password
      - key: DYNACONF_DATABASE__HOST
        fromDatabase:
          name: budgetory-db
          property: host
      - key: DYNACONF_DATABASE__PORT
        fromDatabase:
          name: budgetory-db
          property: port
      - key: DYNACONF_DATABASE__NAME
        fromDatabase:
          name: budgetory-db
          property: database

  - type: web
    name: budgetory-frontend
    runtime: docker
    dockerfilePath: ./frontend/docker/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: budgetory-backend
          type: web
          property: host
      - key: REACT_APP_ACCESS_TOKEN_LIFETIME
        value: "3600"
      - key: REACT_APP_REFRESH_TOKEN_LIFETIME
        value: "86400"

databases:
  - name: budgetory-db
    plan: free