[default]
'ENVIRONMENT.SECRET_KEY' = {must_exist=true}
'ENVIRONMENT.SUPERUSER_API_KEY' = {must_exist=true}
'ENVIRONMENT.ALLOWED_HOSTS' = {must_exist=true}
'ENVIRONMENT.CORS_ORIGIN_WHITELIST' = {must_exist=true}

