default:
  ENVIRONMENT:
    SECRET_KEY: ~
    SUPERUSER_API_KEY: ~
    DEBUG: 1
    DEBUG_TOOLBAR_ENABLED: 1
    ALLOWED_HOSTS:
      - 127.0.0.1
      - localhost
    CORS_ORIGIN_WHITELIST:
      - http://localhost:3000
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: ~
    USER: ~
    PASSWORD: ~
    HOST: ~
    PORT: ~

production:
  dynaconf_merge: true
  ENVIRONMENT:
    DEBUG: 0
    DEBUG_TOOLBAR_ENABLED: 0
    ALLOWED_HOSTS:
      - .onrender.com
    CORS_ORIGIN_WHITELIST:
      - https://budgetory-frontend.onrender.com
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: ~
    USER: ~
    PASSWORD: ~
    HOST: ~
    PORT: ~
